fragment Company on Company {
  id
  name
}

fragment Job on Job {
  id
  title
  description
  location
  salary
  type
  remote
  createdAt
}

fragment Meta on Meta {
  hasMore
  nextCursor
}

query OwnedJobs($input: JobConnectionInput!) {
  ownedJobs(input: $input) {
    data {
      ...Job
      company {
        ...Company
      }
    }
    meta {
      ...Meta
    }
  }
}

query AppliedJobs($input: JobConnectionInput!) {
  appliedJobs(input: $input) {
    data {
      ...Job
      company {
        ...Company
      }
    }
    meta {
      ...Meta
    }
  }
}
